/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.sound.ampache;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int art=0x7f060000;
        public static final int collection=0x7f060003;
        public static final int other=0x7f060002;
        public static final int playing=0x7f060004;
        public static final int prefs=0x7f060005;
        public static final int title=0x7f060001;
    }
    public static final class layout {
        public static final int main=0x7f020000;
        public static final int playlist_item=0x7f020001;
        public static final int playlist_item_simple=0x7f020002;
    }
    public static final class menu {
        public static final int menu=0x7f050000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int collection_label=0x7f04000d;
        public static final int dialog_password_preference=0x7f04000c;
        public static final int dialog_server_preference=0x7f040006;
        public static final int dialog_username_preference=0x7f040009;
        public static final int play_name=0x7f040002;
        public static final int prefs_name=0x7f040001;
        public static final int server_preferences=0x7f040003;
        public static final int summary_password_preference=0x7f04000b;
        public static final int summary_server_preference=0x7f040005;
        public static final int summary_username_preference=0x7f040008;
        public static final int title_password_preference=0x7f04000a;
        public static final int title_server_preference=0x7f040004;
        public static final int title_username_preference=0x7f040007;
    }
    public static final class xml {
        public static final int preferences=0x7f030000;
    }
}
