/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.sound.ampache;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int amdroid_logo=0x7f020000;
        public static final int amdroid_logo_orig=0x7f020001;
    }
    public static final class id {
        public static final int add=0x7f070000;
        public static final int art=0x7f070004;
        public static final int list=0x7f070003;
        public static final int menutext=0x7f070002;
        public static final int other=0x7f070005;
        public static final int pl_clear=0x7f070008;
        public static final int pl_load=0x7f07000a;
        public static final int pl_save=0x7f070009;
        public static final int playing=0x7f070006;
        public static final int prefs=0x7f070007;
        public static final int title=0x7f070001;
    }
    public static final class layout {
        public static final int browsable_item=0x7f030000;
        public static final int main=0x7f030001;
        public static final int playlist=0x7f030002;
        public static final int playlist_item=0x7f030003;
    }
    public static final class menu {
        public static final int collection_menu=0x7f060000;
        public static final int playlist_menu=0x7f060001;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int dialog_password_preference=0x7f05000c;
        public static final int dialog_server_preference=0x7f050006;
        public static final int dialog_username_preference=0x7f050009;
        public static final int play_name=0x7f050002;
        public static final int prefs_name=0x7f050001;
        public static final int server_preferences=0x7f050003;
        public static final int summary_password_preference=0x7f05000b;
        public static final int summary_server_preference=0x7f050005;
        public static final int summary_username_preference=0x7f050008;
        public static final int title_password_preference=0x7f05000a;
        public static final int title_server_preference=0x7f050004;
        public static final int title_username_preference=0x7f050007;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
}
